[project]
name = "dibimbingi-kafka-spark-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.12.2",
    "pyspark==3.5.0",
]
